BEGIN;

TRUNCATE TABLE "users" CASCADE;
TRUNCATE TABLE "transaction" CASCADE;
TRUNCATE TABLE "oauth" CASCADE;
TRUNCATE TABLE "roles" CASCADE;

SELECT SETVAL ((SELECT PG_GET_SERIAL_SEQUENCE('"roles"', 'id')), 1, FALSE);

COMMIT;